# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hassmpris.security.proto import ecdh_pb2 as ecdh__pb2


class ECDHServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientPubkey = channel.unary_unary(
                '/ECDHPackage.ECDHService/ClientPubkey',
                request_serializer=ecdh__pb2.ECDHKey.SerializeToString,
                response_deserializer=ecdh__pb2.Ack.FromString,
                )
        self.ServerPubkey = channel.unary_unary(
                '/ECDHPackage.ECDHService/ServerPubkey',
                request_serializer=ecdh__pb2.Ack.SerializeToString,
                response_deserializer=ecdh__pb2.ECDHKey.FromString,
                )


class ECDHServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClientPubkey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerPubkey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ECDHServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientPubkey': grpc.unary_unary_rpc_method_handler(
                    servicer.ClientPubkey,
                    request_deserializer=ecdh__pb2.ECDHKey.FromString,
                    response_serializer=ecdh__pb2.Ack.SerializeToString,
            ),
            'ServerPubkey': grpc.unary_unary_rpc_method_handler(
                    servicer.ServerPubkey,
                    request_deserializer=ecdh__pb2.Ack.FromString,
                    response_serializer=ecdh__pb2.ECDHKey.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ECDHPackage.ECDHService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ECDHService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClientPubkey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ECDHPackage.ECDHService/ClientPubkey',
            ecdh__pb2.ECDHKey.SerializeToString,
            ecdh__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ServerPubkey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ECDHPackage.ECDHService/ServerPubkey',
            ecdh__pb2.Ack.SerializeToString,
            ecdh__pb2.ECDHKey.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
