# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ecdh.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ecdh.proto',
  package='ECDHPackage',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\necdh.proto\x12\x0b\x45\x43\x44HPackage\"\x19\n\x07\x45\x43\x44HKey\x12\x0e\n\x06pubkey\x18\x01 \x01(\x0c\"\x05\n\x03\x41\x63k2\x81\x01\n\x0b\x45\x43\x44HService\x12\x38\n\x0c\x43lientPubkey\x12\x14.ECDHPackage.ECDHKey\x1a\x10.ECDHPackage.Ack\"\x00\x12\x38\n\x0cServerPubkey\x12\x10.ECDHPackage.Ack\x1a\x14.ECDHPackage.ECDHKey\"\x00\x62\x06proto3'
)




_ECDHKEY = _descriptor.Descriptor(
  name='ECDHKey',
  full_name='ECDHPackage.ECDHKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pubkey', full_name='ECDHPackage.ECDHKey.pubkey', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=52,
)


_ACK = _descriptor.Descriptor(
  name='Ack',
  full_name='ECDHPackage.Ack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['ECDHKey'] = _ECDHKEY
DESCRIPTOR.message_types_by_name['Ack'] = _ACK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ECDHKey = _reflection.GeneratedProtocolMessageType('ECDHKey', (_message.Message,), {
  'DESCRIPTOR' : _ECDHKEY,
  '__module__' : 'ecdh_pb2'
  # @@protoc_insertion_point(class_scope:ECDHPackage.ECDHKey)
  })
_sym_db.RegisterMessage(ECDHKey)

Ack = _reflection.GeneratedProtocolMessageType('Ack', (_message.Message,), {
  'DESCRIPTOR' : _ACK,
  '__module__' : 'ecdh_pb2'
  # @@protoc_insertion_point(class_scope:ECDHPackage.Ack)
  })
_sym_db.RegisterMessage(Ack)



_ECDHSERVICE = _descriptor.ServiceDescriptor(
  name='ECDHService',
  full_name='ECDHPackage.ECDHService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=62,
  serialized_end=191,
  methods=[
  _descriptor.MethodDescriptor(
    name='ClientPubkey',
    full_name='ECDHPackage.ECDHService.ClientPubkey',
    index=0,
    containing_service=None,
    input_type=_ECDHKEY,
    output_type=_ACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ServerPubkey',
    full_name='ECDHPackage.ECDHService.ServerPubkey',
    index=1,
    containing_service=None,
    input_type=_ACK,
    output_type=_ECDHKEY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ECDHSERVICE)

DESCRIPTOR.services_by_name['ECDHService'] = _ECDHSERVICE

# @@protoc_insertion_point(module_scope)
