# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from hassmpris.security.proto import masc_pb2 as masc__pb2


class MASCServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IssueCertificate = channel.unary_unary(
                '/MASCPackage.MASCService/IssueCertificate',
                request_serializer=masc__pb2.IssueCertificateRequest.SerializeToString,
                response_deserializer=masc__pb2.IssueCertificateReply.FromString,
                )


class MASCServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IssueCertificate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MASCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IssueCertificate': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueCertificate,
                    request_deserializer=masc__pb2.IssueCertificateRequest.FromString,
                    response_serializer=masc__pb2.IssueCertificateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'MASCPackage.MASCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class MASCService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IssueCertificate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/MASCPackage.MASCService/IssueCertificate',
            masc__pb2.IssueCertificateRequest.SerializeToString,
            masc__pb2.IssueCertificateReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
